services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=UTC
      - N8N_SECURE_COOKIE=false  # only true if using HTTPS directly
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - soc-net

volumes:
  n8n_data:

networks:
  soc-net:
    external: true

